//
//  ViewController.swift
//  QuizAssignment
//
//  Created by Ashish Pisey on 05/12/21.
//

import UIKit

class ViewController: UIViewController {

    @IBOutlet weak var lblQuestion: UILabel!
    @IBOutlet weak var lblAnswer: UILabel!
    var currentQuestionIndex = 0
    var quizObjArr: [Quiz] = []
    
    let quizBank = [
        ("What is the first step of iOS development?", "Create the user interface. As we create the UI, we will get a better understanding of our application. Then we breath life into our application."),
        ("Why do we use Autolayout?", "We use Autolayout to set constraints on our View objects so that it can adapt to different screen sizes and to different orientations (portrait or landscape)"),
        ("What is the difference between IBAction and IBOutlet?", "Both IBAction and IBOutlets are connections from View elements on our storyboard. IBOutlet connects a proprety in our code to an object in a storyboard while an IBAction connects an event generated by an object in a storyboard to a method in our code."),
        ("What is the Model in MVC responsible for?", "Model objects are responsible for the data of our application. It is important to note that Model objects know nothing about the user interface. An example of a Model could be a list of questions and answers."),
        ("What is the View in MVC responsible for?", "View objects are objects that can be seen by the user (objects you drag into the storyboard). Some examples are labels and buttons."),
        ("What is the Controller in MVC responsible for?", "Controller objects facilitate the communication between the Model and the View since the Model and the View should never directly talk to each other (remember the Model knows nothing about the user interface).")
    ]
    
    //let fullname = ("Ashish", "Pisey")
    
    override func viewDidLoad() {
        super.viewDidLoad()
        // Do any additional setup after loading the view.
        //print(fullname.1)
        getQuizObjArr()
        currentQuestionIndex = 0
        updateUIForQuestion()
        
    }
    
    func getQuizObjArr() {
        for quizTuple in quizBank {
            let quizObj = Quiz.init(question: quizTuple.0, answer: quizTuple.1)
            quizObjArr.append(quizObj)
        }
    }
    
    func updateUIForQuestion() {
        //let questionTuple = quizBank[currentQuestionIndex]
        let quizObj = quizObjArr[currentQuestionIndex]
        lblQuestion.text = quizObj.question
        lblAnswer.text = ""
    }

    @IBAction func btnAnswerPressed(_ sender: UIButton) {
        //let questionTuple = quizBank[currentQuestionIndex]
        let quizObj = quizObjArr[currentQuestionIndex]
        lblAnswer.text = quizObj.answer
    }
    
    @IBAction func btnNextPressed(_ sender: UIButton) {
        currentQuestionIndex += 1
        updateUIForQuestion()
    }
    
}

struct Quiz {
    let question: String
    let answer: String
}
