# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MyTimeVisualizer' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MyTimeVisualizer

  target 'MyTimeVisualizerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MyTimeVisualizerUITests' do
    # Pods for testing
  end

  pod 'Charts'
end
